#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-cons
Version  : 0.4.5
Release  : 6
URL      : https://files.pythonhosted.org/packages/1e/b1/263faca4ab3dab8859f0d725f2b64e3a0182dbf9a8ae156209d7a2b4b9de/cons-0.4.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/1e/b1/263faca4ab3dab8859f0d725f2b64e3a0182dbf9a8ae156209d7a2b4b9de/cons-0.4.5.tar.gz
Summary  : An implementation of Lisp/Scheme-like cons in Python.
Group    : Development/Tools
License  : LGPL-3.0
Requires: pypi-cons-license = %{version}-%{release}
Requires: pypi-cons-python = %{version}-%{release}
Requires: pypi-cons-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(logical_unification)

%description
# Python `cons`
        
        An implementation of [`cons`][cons] in Python.
        
        ## Usage and Design

%package license
Summary: license components for the pypi-cons package.
Group: Default

%description license
license components for the pypi-cons package.


%package python
Summary: python components for the pypi-cons package.
Group: Default
Requires: pypi-cons-python3 = %{version}-%{release}

%description python
python components for the pypi-cons package.


%package python3
Summary: python3 components for the pypi-cons package.
Group: Default
Requires: python3-core
Provides: pypi(cons)
Requires: pypi(logical_unification)

%description python3
python3 components for the pypi-cons package.


%prep
%setup -q -n cons-0.4.5
cd %{_builddir}/cons-0.4.5
pushd ..
cp -a cons-0.4.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656367139
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-cons
cp %{_builddir}/cons-0.4.5/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-cons/f45ee1c765646813b442ca58de72e20a64a7ddba
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-cons/f45ee1c765646813b442ca58de72e20a64a7ddba

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
